language: c++
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script: 
  - cmake -DBENCHMARK_ENABLE_TESTING=OFF -DCMAKE_CXX_COMPILER=/usr/bin/g++-6 -DCMAKE_CC_COMPILER=/usr/bin/gcc-6 .
  - cmake --build tests
  - ./tests/tests


