language: c++
sudo: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script: 
  - CXX=/usr/bin/g++-6 CC=/usr/bin/gcc-6 cmake -DBENCHMARK_ENABLE_TESTING=OFF .
  - cmake --build tests
  - ./tests/tests


